# Netlify Configuration File

[build]
  # Directory with the serverless functions
  functions = "netlify/functions"
  
  # Publish directory (where your static files are)
  publish = "."

[build.environment]
  # Node version for building
  NODE_VERSION = "18"

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development settings
[dev]
  port = 8888
  publish = "."
  autoLaunch = false

# Function configuration
[functions]
  # Directory where Netlify will look for serverless functions
  directory = "netlify/functions"
  
  # Node bundler for better performance
  node_bundler = "esbuild"

# Environment variable hints (actual values set in Netlify dashboard)
[context.production.environment]
  # Apify Configuration
  # APIFY_TOKEN = "Set in Netlify dashboard"
  # APIFY_TIKTOK_TASK_ID = "Set in Netlify dashboard (optional)"
  # APIFY_INSTAGRAM_TASK_ID = "Set in Netlify dashboard (optional)"
  # APIFY_YOUTUBE_TASK_ID = "Set in Netlify dashboard (optional)"
  
  # AI Provider APIs
  # OPENAI_API_KEY = "Set in Netlify dashboard"
  # ANTHROPIC_API_KEY = "Set in Netlify dashboard"
  # GOOGLE_API_KEY = "Set in Netlify dashboard (for Gemini)"
  # GROK_API_KEY = "Set in Netlify dashboard"